version: '3.8'

services:
  postgres-db:
    image: postgres:latest  
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Vamshi57 
      - POSTGRES_DB=ABC 
    ports:
      - "5432:5432"  
    restart: unless-stopped  
